show_schedules_route:
  path: /
  controller: App\Controller\MainController::index
  methods: GET

get_create_schedule_route:
  path: /schedules/create
  controller: App\Controller\ScheduleController::show
  methods: GET

post_create_schedule_route:
  path: /schedules/create
  controller: App\Controller\ScheduleController::create
  methods: POST