show_schedules_route:
  path: /
  controller: App\Controller\MainController::index
  methods: GET

show_schedule_route:
  path: /schedules
  controller: App\Controller\ScheduleController::create
  methods: POST

